language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - EXTRAS="N"
  - EXTRAS="Y"

install:
    - if [ $EXTRAS == 'Y' ]; then pip install -r supported_pkgs.txt; fi
    - pip install coveralls

script:
  - python -bb -m coverage run -p --source=serialize --omit="*test*" setup.py test
  - coverage combine
  - coverage report -m

after_script:
  - coveralls --verbose

